### ISSUE TITLE
yandex_mdb_postgresql_cluster resource is missing

### ISSUE THREAD

**Issue by imtpot** [pulumi/pulumi-yandex#60]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hello! Can't found yandex_mdb_postgresql_cluster resource, it seams missing. Can you add it please?

**Comment by jkodroff** [comment]
@stack72 The comments around this resource indicate that we're skipping for 2 reasons:

1. The docs are broken and end up generating in an indeterminate manner.
2. Go SDK linting fails

I get the first one, which we can solve by overriding the docs (which we're doing in the commented out code). I'm not sure why Go SDK linting would fail and what conditions would need to change in order for us to map the resource.

Can you explain more?

**Comment by iwahbe** [comment]
Closing as this repo will be archived.
